# version: '3.8'
services:
# nginx ------------------------------------------------------------
  nginx:
    build: ./requirements/nginx/
    container_name: nginx
    depends_on:
      - wordpress
    ports:
      - "443:443"
    env_file:
      - .env
    volumes:
      - wordpress_data:/var/www/html/
    restart: unless-stopped
    networks:
      inception:

# wordpress ------------------------------------------------------------
  wordpress:
    build: ./requirements/wordpress/.
    container_name: wp-php
    depends_on:
      - mariadb
    volumes:
      - wordpress_data:/var/www/html/
    env_file:
      - .env
    restart: unless-stopped
    networks:
      inception:

# mariadb ------------------------------------------------------------
  mariadb:
    build: ./requirements/mariadb/.
    container_name: mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    env_file:
      - .env
    restart: unless-stopped
    networks:
      inception:

networks:
  inception:
    name: inception-network
    driver: bridge

volumes:
  mariadb_data:
    name: mariadb
    # (以下省略)

  wordpress_data:
    name: wordpress
    # (以下省略)
